#!/usr/bin/env python3
"""
Create the project folder structure for a new website-builder-pipeline build.

Usage (from Python):
    from scaffold_project import scaffold
    scaffold(
        project_dir="./my-project",
        brand=brand_dict,
        survey=survey_dict,
        env_overrides={"KIE_AI_API_KEY": "..."},
    )

CLI:
    python scaffold-project.py ./my-project --brand brand.json --survey survey.json
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parent  # .../website-builder-pipeline/references
ENV_TEMPLATE = SKILL_DIR / "env-template.env"


def scaffold(
    project_dir: str | Path,
    brand: dict,
    survey: dict,
    env_overrides: dict[str, str] | None = None,
) -> Path:
    root = Path(project_dir).resolve()
    root.mkdir(parents=True, exist_ok=True)

    # 1. Write brand.json
    (root / "brand.json").write_text(
        json.dumps(brand, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # 2. Create sub-folders
    (root / "assets").mkdir(exist_ok=True)
    (root / "inspiration").mkdir(exist_ok=True)

    # 3. Write .env from template + overrides + existing environment values
    env_text = ENV_TEMPLATE.read_text(encoding="utf-8") if ENV_TEMPLATE.exists() else ""
    merged = _merge_env(env_text, env_overrides or {})
    (root / ".env").write_text(merged, encoding="utf-8")

    # 4. Write README.md (survey summary + next steps)
    readme = _build_readme(brand, survey)
    (root / "README.md").write_text(readme, encoding="utf-8")

    # 5. Write build-plan.md (the master prompt that Claude Code will execute)
    plan = _build_plan(brand, survey)
    (root / "build-plan.md").write_text(plan, encoding="utf-8")

    return root


def _merge_env(template_text: str, overrides: dict[str, str]) -> str:
    """Merge overrides into template, also pulling from current environment."""
    out_lines: list[str] = []
    for line in template_text.splitlines():
        stripped = line.strip()
        if "=" in line and not stripped.startswith("#"):
            key = line.split("=", 1)[0].strip()
            if key in overrides and overrides[key]:
                out_lines.append(f"{key}={overrides[key]}")
            elif os.environ.get(key):
                out_lines.append(f"{key}={os.environ[key]}")
            else:
                out_lines.append(line)
        else:
            out_lines.append(line)
    return "\n".join(out_lines) + "\n"


def _build_readme(brand: dict, survey: dict) -> str:
    name = brand.get("name", "Untitled Project")
    tagline = brand.get("tagline", "")
    vibe = survey.get("vibe", "unspecified")
    sections = ", ".join(survey.get("sections", []))
    deploy = survey.get("deploy", "none")

    return f"""# {name}

{tagline}

Generated by the website-builder-pipeline skill on {_today()}.

## Survey Summary

- Vibe: {vibe}
- Sections: {sections}
- Deploy target: {deploy}
- Budget tier: {survey.get('budget', 'unspecified')}
- SEO tier: {survey.get('seo', 'basic')}

## Files

- `brand.json` — extracted brand identity
- `assets/hero.mp4` — Kling 3.0 scroll animation
- `assets/hero-mobile.jpg` — mobile still fallback
- `assets/start-frame.webp` — NanoBanana start frame
- `assets/end-frame.webp` — NanoBanana end frame
- `inspiration/` — competitor HTML sources + screenshots
- `build-plan.md` — the master prompt that drives the build
- `.env` — API keys (not committed)

## Next Steps

1. Review `build-plan.md`
2. In Claude Code, run: `@build-plan.md` or let the skill invoke it
3. Claude will enter Plan Mode first, show the plan, then execute
4. Dev server will spin up when done
5. Iterate with specific feedback
6. Run the SEO pass
7. Deploy to {deploy}
"""


def _build_plan(brand: dict, survey: dict) -> str:
    """The master build prompt that Claude Code executes. Filled from survey."""
    return f"""# Build Plan — {brand.get('name', 'Project')}

Act as an expert front-end engineer. Use the taste-skill and front-end design
skill for this build. Start in Plan Mode, show me the plan, wait for my
approval, then switch to Bypass Permissions and execute.

## Brand

{json.dumps(brand, indent=2, ensure_ascii=False)}

## Survey Answers

{json.dumps(survey, indent=2, ensure_ascii=False)}

## Assets

- Hero video: `assets/hero.mp4` (use for scroll-driven animation, Apple-style
  frame-by-frame on scroll via ffmpeg-extracted WebP frames)
- Mobile still: `assets/hero-mobile.jpg` (fallback for phones — do NOT load
  the MP4 on mobile)
- Start frame: `assets/start-frame.webp`
- End frame: `assets/end-frame.webp`
- Inspiration: `inspiration/` — use the HTML sources as structural scaffolding
  and the screenshots as visual references. Do NOT visually copy — use them to
  inform layout and rhythm.

## Sections to Build

{chr(10).join(f"- {s}" for s in survey.get('sections', []))}

## Vibe + Dials

Apply the {survey.get('vibe', 'Minimalist')} archetype with taste-skill dials:
- DESIGN_VARIANCE: {survey.get('design_variance', 7)}
- MOTION_INTENSITY: {survey.get('motion_intensity', 5)}
- VISUAL_DENSITY: {survey.get('visual_density', 4)}

Fonts: {survey.get('heading_font', 'Geist')} (heading) + {survey.get('body_font', 'Inter')} (body)

Colors (from brand.json):
{_colors_block(brand)}

## Critical Rules

1. Dark mode by default (unless brand colors dictate otherwise)
2. Scroll-driven hero animation using ffmpeg frame extraction
3. Mobile-responsive (still image fallback, not MP4)
4. No AI clichés: Elevate, Seamless, Unlock, Empower
5. No Inter/Roboto/Arial (use the specified fonts)
6. No pure black (#000000) — use dark gray tones
7. No centered hero sections (unless vibe is Editorial Luxury)
8. GPU-safe animation only (transform + opacity)
9. Staggered reveal animations on scroll
10. Loading/empty/error states for every interactive element
11. End with: spin up a dev server on localhost

## Deliverable

A working dev server at localhost, fully functional, scroll animation working,
all sections present, responsive, accessible (WCAG 2.2 AA minimum). Do NOT do
the SEO pass yet — that's a separate step after I approve the initial build.
"""


def _colors_block(brand: dict) -> str:
    colors = brand.get("colors", {}) or {}
    if not colors:
        return "  (use vibe archetype defaults)"
    return "\n".join(f"  - {k}: {v}" for k, v in colors.items())


def _today() -> str:
    from datetime import date
    return date.today().isoformat()


def _cli() -> None:
    parser = argparse.ArgumentParser(description="Scaffold a website-builder-pipeline project")
    parser.add_argument("project_dir")
    parser.add_argument("--brand", required=True, help="Path to brand.json")
    parser.add_argument("--survey", required=True, help="Path to survey.json")
    args = parser.parse_args()

    brand = json.loads(Path(args.brand).read_text(encoding="utf-8"))
    survey = json.loads(Path(args.survey).read_text(encoding="utf-8"))
    out = scaffold(args.project_dir, brand, survey)
    print(f"Scaffolded: {out}")


if __name__ == "__main__":
    try:
        _cli()
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
